# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b668dc223538943dada09d59d253868b585092956555a10294549107662835833a2442f44447a04fa4caa23fb8c95262651468e7a07c0058b1161d4cb7aa0be

test:
  secret_key_base: f24d8a9d921794c8b7593be7cb374360dfb22536e1a403a9e857c94e14265b46cdd86377b876194a067a27afebd3fcc682d57fa5896fbed502909dc44b0e1366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
